### ISSUE TITLE
delete route for projects not working?

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#26]
After setting up the **projects** scaffolding in PR #24, `new`, `view` , `edit`, `index`, and `delete` routes (and corresponding views) were automatically created.

First four routes seem to be working alright, I can create a new project, I can view the index of created projects, I can edit a project that has been created and update it, I can view a summary of a project that has been created. However when clicking on the automatically generated link for the `delete` route (which should make a `DELETE` request, as opposed to `GET` or `PATCH`), the project is not deleted. From examining the controllers it seems that there should be some kind of prompt, whether or not you confirm that you really want to delete the project. That's a good idea so you don't accidentally delete a project and have to start all over again. However I'm not seeing this prompt anywhere. I'd say this needs to be looked into. CSS / positioning problem? Or controller logic problem? Perhaps those with more experience in rails would know where to look to fix this? @mftruso @mkasberg

**Comment by kas-catholic** [comment]
I bet we're either missing or somehow messed up rails.js. This `link_to` action with `method: :delete` relies on that js lib to work correctly, and is just making a GET request without the JS helper (as you can see in the network tab of Chrome or Firefox debug tools), which is why nothing is being deleted.

https://guides.rubyonrails.org/v4.1/working_with_javascript_in_rails.html#built-in-helpers
