### ISSUE TITLE
should we use `bundle --binstubs` ?

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#30]
The **rails** executable wrapper which is included in the application `bin` folder, does this come from `gem install rails`? Or does it come from `bundle install`? Doesn't seem to me that it comes from `bundle install`, because on a fresh setup, I still wasn't able to invoke `rails --version` directly after `bundle install`, I still needed to invoke `bundle exec rails --version`.

I'm guessing we should avoid installing gems directly in our local development environments, since they might have different versions compared to the gems that are bundled with the application?

As I'm reading up here and there I found this utility `bundle --binstubs` which should create wrappers in the `bin` folder for the gems that are installed through bundler. That way you should be able to invoke `rails --version` directly, or `i18n-tasks` commands directly, without having to use `bundle exec` each time.

However, when trying to use `bundle --binstubs`, I'm then seeing a constant warning about how a `rails` executable is included by default in rails apps, and `bundle --binstubs` is overwriting it, which may not be a desired behaviour. I'm wondering if this warning message is coming from the fact that the `rails` gem was accidentally installed directly, rather than with bundler? Or is this warning message giving some actually useful information about how `bundle --binstubs` overwrites a `rails` executable which bundler itself provided? Or can the warning be ignored?

Or, should we avoid using `bundle --binstubs`, and simply create the stubs that we would like for single gems, [as suggested here](https://coderwall.com/p/vhfxia/generate-only-the-binstubs-that-your-project-needs)?

**Comment by kas-catholic** [comment]
I believe our binstubs are already checked in correctly: https://github.com/opensourcecatholic/marriage-booklet/tree/main/bin The `bin/rails` executable provided there was generated by `rails new` when we created the project, from my own globally-installed rails gem.

> I'm guessing we should avoid installing gems directly in our local development environments, since they might have different versions compared to the gems that are bundled with the application?

Not necessarily - Bundler is actually pretty good at finding the gems it needs, and I think using `bundle exec` or similar should always be able to get you out of a situation where there's a conflict. You should feel free to install whatever you need.

We shouldn't need to run `bundle --binstubs` to generate anything, it should already be there. That's why it's giving you the warning - it would overwrite the `bin/rails executable that's already checked in to our repo.

Notably, `marriage-booklet/bin/rails` is not in your `$PATH` (and it generally shouldn't be). I most frequently run `bin/rails` from the `marriage-booklet` project directory, but `bundle exec rails` is also fine. Simply `rails` will also work _if the rails version installed to `$(gem env home)` matches the version required in `Gemfile`_, but this won't always be the case depending if you have a more recent version (or none?) globally installed in your rbenv environment. You're welcome to `gem install rails` if you want a version of rails in your path.

**Comment by JohnRDOrazio** [comment]
For example, when adding the `i18n-tasks` gem to the bundle, no stub is created after `bundle install`, which means I have to run `bundle exec i18n-tasks _task_` for each task, unless I also `gem install i18n-tasks`. Or maybe I could just `bundle binstub i18n-tasks`.

**Comment by kas-catholic** [comment]
Oh, for gems that we've added like that (or anything that's missing, really), feel free to run `bundle binstubs i18n-tasks` to generate the stubs and then check them in to the repo. Then, from that point on, you'd be able to run `bin/i18n-tasks ...`
